# Generated by Django 5.0.6 on 2024-11-25 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_alter_perfilusuario_complemento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
